name: test-workflow
on:
  push:
     branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fdapde-docker:latest
    steps:
    - uses: actions/checkout@v2
    - name: RunOne
      run: |
        cd src/core/NLA/
        cmake CMakeLists.txt
